[build]
  publish = "/"
  command = "# no build command"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[dev]
  framework = "#custom"
  command = "npm start"
  targetPort = 8888
  port = 8888
  publish = "/"
  autoLaunch = true

[[plugins]]
  package = "@netlify/plugin-lighthouse"

[build.environment]
  NODE_VERSION = "18"